sonar.projectKey=ktps-2
sonar.working.directory=C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\PC\\Desktop\\KTPS-2
sonar.pullrequest.cache.basepath=C:\\Users\\PC\\Desktop\\KTPS-2
sonar.sources=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\App.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\app.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\babel.config.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\constants.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\package-lock.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\package.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.github\\workflows\\e2e.yml",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.github\\workflows\\unitTests.yml",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\FindFriends.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\Friends.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\GroupInfo.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\GroupList.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\Login.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\Main.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\Notifications.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.App\\components\\Register.js",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.vs\\KTPS\\v17\\DocumentLayout.json"

EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.projectKey=ktps-2:EE13F87D-43F5-418E-BBA9-792632E16D7F
EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.projectName=KTPS.Model
EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.projectBaseDir=C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model
EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.sourceEncoding=utf-8
EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.tests=
EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.sources=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Calculation\\GuestCalculation.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Calculation\\UserCalculation.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Groups\\GroupBasic.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Groups\\GroupMember.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Guests\\Guest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Items\\ItemBasic.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Items\\ItemMemberBasic.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Notifications\\Notification.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Registration\\RegistrationBasic.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\AddGuestRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\CreateItemRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\CreateNotificationRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\DeleteFriendRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\DeleteGroupRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\EditGroupRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\EditItemRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\FindFriendRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\ForgotPasswordRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\LeaveGroupRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\LoginRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\NewGroupRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\RegistrationAuthRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\RegistrationStartRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\RemoveGroupMembersRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\ResetPasswordAuthRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\ResetPasswordRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Requests\\RespondNotificationRequest.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Responses\\CalculationResponse.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\Responses\\GetGroupMembersResponse.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\ServerResult.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\User\\UserBasic.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Entities\\User\\UserMinimal.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Helpers\\PasswordHelper.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Helpers\\RandomString.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Helpers\\RepositoryHelper.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Friends\\FriendsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Friends\\IFriendsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\GroupMembers\\GroupMembersRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\GroupMembers\\IGroupMembersRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Groups\\GroupsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Groups\\IGroupsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Guests\\GuestsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Guests\\IGuestsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\IRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Items\\IItemMemberRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Items\\IItemsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Items\\ItemMemberRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Items\\ItemsRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Notifications\\INotificationRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Notifications\\NotificationRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\PasswordReset\\IPasswordResetRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\PasswordReset\\PasswordResetRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Registration\\IRegistrationRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Registration\\RegistrationRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\Repository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\User\\IUserRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Repositories\\User\\UserRepository.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Calculation\\CalculationService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Calculation\\ICalculationService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Friends\\FriendsService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Friends\\IFriendsService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Groups\\GroupsService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Groups\\IGroupsService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Items\\IItemMembersService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Items\\IItemsService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Items\\ItemMembersService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Items\\ItemsService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Login\\ILoginService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Login\\LoginService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Notifications\\INotificationService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Notifications\\NotificationService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Registration\\IRegistrationService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\Registration\\RegistrationService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\User\\IUserService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\Services\\User\\UserService.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\obj\\KTPS.Model.csproj.nuget.dgspec.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\obj\\project.assets.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\bin\\Debug\\net6.0\\KTPS.Model.deps.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Model\\obj\\Debug\\net6.0\\KTPS.Model.sourcelink.json"

EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\0"
EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\0\\Issues.json"

EE13F87D-43F5-418E-BBA9-792632E16D7F.sonar.working.directory=C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\.sonar\\mod0
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.projectKey=ktps-2:50FECA68-7254-4AAC-9163-78D26514AF6E
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.projectName=KTPS.Server.WebAPI
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.projectBaseDir=C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.sourceEncoding=utf-8
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.tests=
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.sources=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\appsettings.Development.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\appsettings.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\KTPS.Server.WebAPI.csproj.nuget.dgspec.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\project.assets.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Properties\\launchSettings.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\bin\\Debug\\net6.0\\appsettings.Development.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\bin\\Debug\\net6.0\\appsettings.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\bin\\Debug\\net6.0\\KTPS.Server.WebAPI.deps.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\bin\\Debug\\net6.0\\KTPS.Server.WebAPI.runtimeconfig.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\Debug\\net6.0\\KTPS.Server.WebAPI.sourcelink.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\Debug\\net6.0\\staticwebassets.build.json",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Controllers\\FriendsController.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Controllers\\GroupsController.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Controllers\\LoginController.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Controllers\\NotificationController.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Controllers\\RegistrationController.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Controllers\\ShoppingListController.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\Program.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\Debug\\net6.0\\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\Debug\\net6.0\\KTPS.Server.WebAPI.AssemblyInfo.cs",\
"C:\\Users\\PC\\Desktop\\KTPS-2\\KTPS.Server.WebAPI\\obj\\Debug\\net6.0\\KTPS.Server.WebAPI.MvcApplicationPartsAssemblyInfo.cs"

50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\1"
50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\1\\Issues.json"

50FECA68-7254-4AAC-9163-78D26514AF6E.sonar.working.directory=C:\\Users\\PC\\Desktop\\KTPS-2\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.exclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.visualstudio.enable=false

sonar.modules=EE13F87D-43F5-418E-BBA9-792632E16D7F,50FECA68-7254-4AAC-9163-78D26514AF6E

